modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Harleyoc1/PotionsExpansion/issues"

[[mods]]
modId="potionsexpansion"
version="${file.jarVersion}"
displayName="Potions Expansion"
updateJSONURL="https://github.com/Harleyoc1/PotionsExpansion/blob/1.16.x/version_info.json?raw=true"
displayURL="http://harleyoconnor.com/"
logoFile="null.png"
credits=""
authors="Harley O'Connor, Archie Adams"
description='''
A mod that expands on the vanilla potion system.
'''

[[dependencies.potionsexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.potionsexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
