modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://null.com/" #optional
[[mods]] #mandatory
modId="potionsexpansion" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Potions Expansion" #mandatory
updateJSONURL="http://harleyoconnor.com/" #optional
displayURL="http://null.com/" #optional
logoFile="null.png" #optional
credits="" #optional
authors="Harley O'Connor, Archie Adams" #optional
description='''
A mod that expands on the vanilla potion system.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
